class_name WaterHazard
extends Node3D
## Analytic water surface, sampled only from the body's force-integration callback.
## A half-space cannot be skipped by falling through a thin Area3D in one tick.

signal water_entered(position: Vector3, impact_speed: float)

@export var enabled: bool = true
@export var surface_path: NodePath
@export var half_extent := Vector2(1500.0, 1500.0)
@export_range(0.0, 2.0, 0.01) var immersion_depth: float = 0.3
@export_range(0.0, 3.0, 0.05) var respawn_delay: float = 0.75

var _surface: Node3D


func _ready() -> void:
	# The ocean mesh is generated by Scenery before this node becomes ready.
	if not surface_path.is_empty():
		_surface = get_node_or_null(surface_path) as Node3D
		if _surface == null:
			push_warning("WaterHazard surface is missing; using its own height.")


func surface_level() -> float:
	return _surface.global_position.y if is_instance_valid(_surface) else global_position.y


func sample(center: Vector3, axle: Vector3, major_radius: float, minor_radius: float) -> Dictionary:
	var level := surface_level()
	var vertical_radius := major_radius * sqrt(maxf(0.0, 1.0 - axle.y * axle.y)) + minor_radius
	var bottom := center.y - vertical_radius
	var local_center := center - global_position
	var in_bounds := absf(local_center.x) <= half_extent.x and absf(local_center.z) <= half_extent.y
	# The shader's small +/-0.26 m ripples are cosmetic. The default 0.30 m
	# margin requires real immersion below even a trough, not a passing wave tip.
	return {"submerged": enabled and in_bounds and bottom <= level - immersion_depth,
		"position": Vector3(center.x, level + 0.04, center.z), "depth": level - bottom}
